# Site metadata
name: 根号三
bio: "O ever youthful, O ever weeping."
avatar: "https://avatars0.githubusercontent.com/u/8622362?v=3&s=460"

# Article
defaultAuthor: 根号三 # 文章默认作者

# Site SEO
language: zh-cmn-Hans # 网站使用的语言
SEOTitle: sqrtthree's blog | 根号三的博客
keyword: "前端 前端工程师 HTML5 CSS3 Javascript React Vue Node.js Go Docker" # 网站关键词
description: "web 开发者, 擅长各项前端技能，深入研究 web 端开发与前端性能, 并对 Nodejs 及 Go 服务端技术栈有深入了解。" # 网站描述

# Site settings
favicon: https://assets-cdn.github.com/favicon.ico
bgOfHomeHeader: http://7xl8me.com1.z0.glb.clouddn.com/home.jpg
navbar:
  showDefaultItems: true
  external:
    - { name: "GitHub", to: "https://github.com/sqrthree/lite" }

aboutPage:
  show: true
  content: "
    如果我能够满足只吃清汤粉的幸福，我也绝对不会再去羡慕大城市一分一秒。


    但我偏偏一生放荡不羁爱自由，喜欢上了吃锅包肉和溜肉段。
  "

limitOfFeaturedTags: 2

# SNS Link
snsLink:
  - { icon: "github", to: "https://github.com/sqrthree" }
  - { icon: "twitter", to: "https://twitter.com/sqrtthree" }
  - { icon: "weibo", to: "http://weibo.com/sqrtthree" }
  - { text: "知", to: "https://www.zhihu.com/people/sqrtthree" }
  - { icon: "envelope-o", to: "sqrtthree@foxmail.com" }

contact:
  - { name: "Wechat", value: "511249910" }
  - { name: "Mail", value: "imsqrtthree@gmail.com" }

friends:
  - { name: "GitHub", to: "https://github.com/sqrthree" }
  - { name: "FETalk", to: "https://zhuanlan.zhihu.com/FETalk" }

externalItemOfFooter:
  title: "Open Source"
  list:
    - { name: "sqrthree.github.io", to: "https://github.com/sqrthree/sqrthree.github.io" }
    - { name: "awesome-npm-packages", to: "https://github.com/sqrthree/awesome-npm-packages" }
    - { name: "comeon", to: "https://github.com/sqrthree/comeon" }
    - { name: "lite", to: "https://github.com/sqrthree/lite" }
    # and more...

donation:
  status: true
  channel:
    alipay: http://7xl8me.com1.z0.glb.clouddn.com/alipay.JPG
    wechat: http://7xl8me.com1.z0.glb.clouddn.com/wechat_receive_money.JPG

share: true

analytics:
  google: "UA-64863915-1"
  baidu: 'be6e4b8e6af93860f98b001aab5cbe79'

deploy:
  github:
    username: sqrthree
    repo: sqrthree.github.io
    branch: master
