name: '根号三'
bio: 'O ever youthful, O ever weeping.'
cover: ''
social:
  - name: github
    url: https://github.com/sqrthree
  - name: twitter
    url: https://twitter.com/sqrtthree

# Site SEO
SEOTitle: sqrtthree's blog | 根号三的博客
keyword: '前端 前端工程师 HTML5 CSS3 Javascript React Vue Node.js Go Docker'
description: 'web 开发者, 擅长各项前端技能，专注于 web 端开发与前端性能, 并对 Nodejs 及 Go 服务端技术栈深感兴趣。'
thumbnail: ''

# Site settings
favicon: ''

analytics:
  google: 'UA-64863915-1'

deploy:
  github:
    username: 'sqrthree'
    repo: 'sqrthree.github.io'
    branch: master
